#pragma once

#define FAILED(status) (status != STATUS_SUCCESS)

enum KeStatus
{
    /* General */
    STATUS_SUCCESS = 0,
    STATUS_FAILURE,
    STATUS_NOT_FOUND,

    /* Function parameters */
    STATUS_INVALID_PARAMETER,
    STATUS_NULL_PARAMETER,
    STATUS_INAVLID_HANDLE,

    /* Memory */
    STATUS_ALLOC_FAILED,
    STATUS_INVALID_VIRTUAL_USER_ADDRESS,
    STATUS_PHYSICAL_MEMORY_FULL,
    STATUS_PROCESS_HEAP_LIMIT_REACHED,

    /* IPC */
    IPC_STATUS_ID_STRING_ALREADY_USED,
    IPC_STATUS_SERVER_NOT_FOUND,

    /* HANDLE */
    STATUS_HANDLE_ALREADY_EXIST,

    STATUS_UNEXPECTED,
};